services:
  bot:
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "ps", "aux", "|", "grep", "python"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3 